[controlPlane]
# ec2-group-23-node-4
34.254.23.101 server_role=control-plane

[worker]
# ec2-group-23-node-2
52.213.136.208 server_role=worker
# ec2-group-23-node-3
3.254.114.4 server_role=worker
# ec2-group-23-node-1
108.131.55.2 server_role=worker

