[kube1]
34.254.23.101 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/kubequest-epitech-group-23.pem server_role=kube1 ansible_ssh_common_args='-o StrictHostKeyChecking=no'
[kube2]
3.249.52.79 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/kubequest-epitech-group-23.pem server_role=kube2 ansible_ssh_common_args='-o StrictHostKeyChecking=no'
[monitoring]
34.245.173.145 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/kubequest-epitech-group-23.pem server_role=monitoring ansible_ssh_common_args='-o StrictHostKeyChecking=no'
[ingress]
54.155.249.127 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/kubequest-epitech-group-23.pem server_role=Ingress ansible_ssh_common_args='-o StrictHostKeyChecking=no'