---
- name: Install containerd, Kubeadm, Kubelet and Kubectl
  hosts: all
  become: true
  tags: setup
  roles:
    - Deploy_Containerd
    - Deploy_Kube

- name: Configure Master Node
  hosts: kube1
  become: true
  tags: setup
  roles:
    - Init_Kube

- name: Join Worker Nodes to Cluster
  hosts: kube2 monitoring ingress
  become: true
  tags: setup
  roles:
    - Join_Cluster

- name: Configure Registry on all nodes
  hosts: all
  become: true
  tags: update
  roles:
    - Config_Registry

- name: Deploy Services
  hosts: kube1
  become: true
  tags: services
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  roles:
    - Deploy_Traefik
    - Deploy_Argocd

- name: Deploy ArgoCD
  hosts: kube1
  become: true
  tags: argo
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  roles:
    - Deploy_Argocd

- name: Delete services
  hosts: kube1
  become: true
  tags: delete
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  roles:
    - Delete_Traefik
    - Delete_Argocd
    - Delete_App