# roles/install_kube/tasks/main.yml
---
- name: Add Kubernetes repository
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://pkgs.k8s.io/core:/stable:/v1.31/rpm/
      enabled=1
      gpgcheck=1
      gpgkey=https://pkgs.k8s.io/core:/stable:/v1.31/rpm/repodata/repomd.xml.key
    mode: "0644"

- name: Install kubeadm, kubelet and kubectl
  ansible.builtin.dnf:
    name:
      - kubeadm
      - kubelet
      - kubectl
    state: present

- name: Enable and start kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: true

- name: Install Helm
  shell: |
    curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm
  become: true