apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: app
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  APP_KEY: "ta-clé-app-laravel"
  DB_PASSWORD: "kubequest"
  DB_USERNAME: "kubequest"