apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: app
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  APP_KEY: "base64:HgUcutbtcznVs5JBjmuTDTxj0zUwseUsh0NU/Lw679c="
  DB_PASSWORD: "kubequest"
  DB_USERNAME: "kubequest"