apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: app
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
type: Opaque
stringData:
  APP_KEY: "base64:DJYTvaRkEZ/YcQsX3TMpB0iCjgme2rhlIOus9A1hnj4="
  DB_PASSWORD: "app_password"
  mysql-root-password: "app_root_password"
  mysql-password: "app_password"
