apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql-local
  resources:
    requests:
      storage: 10Gi
