#SPDX-License-Identifier: MIT-0
---
# tasks file for Delete_Argocd
- name: Uninstall ArgoCD Helm release
  kubernetes.core.helm:
    name: argocd
    release_namespace: argocd
    state: absent
    wait: true

- name: Delete ArgoCD namespace
  kubernetes.core.k8s:
    kind: Namespace
    name: argocd
    state: absent